/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cloud_logic_custom": [
        {
            "name": "agroshubapi",
            "endpoint": "https://qmubvi68z7.execute-api.eu-north-1.amazonaws.com/dev",
            "region": "eu-north-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-north-1:bb4acd1c-677f-4feb-8ef9-f36f6570b902",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_WjU5eYdGV",
    "aws_user_pools_web_client_id": "25omlqjpct9a4b7gomkgtti9pf",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "PHONE_NUMBER"
    ],
    "aws_dynamodb_all_tables_region": "eu-north-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "invoicetable-dev",
            "region": "eu-north-1"
        },
        {
            "tableName": "itemscategeory-dev",
            "region": "eu-north-1"
        },
        {
            "tableName": "items-dev",
            "region": "eu-north-1"
        },
        {
            "tableName": "maxdata-dev",
            "region": "eu-north-1"
        },
        {
            "tableName": "organization-dev",
            "region": "eu-north-1"
        },
        {
            "tableName": "purchasedorder-dev",
            "region": "eu-north-1"
        },
        {
            "tableName": "salesorder-dev",
            "region": "eu-north-1"
        },
        {
            "tableName": "user-dev",
            "region": "eu-north-1"
        }
    ]
};


export default awsmobile;
